from pydantic import BaseModel
from typing import List
from datetime import datetime

class CreateAdvertisingResponse(BaseModel):
    id: str

class AdvertisingDTO(BaseModel):
    name: str
    user_id: str
    product_id: int
    status: str
    expiration_timestamp: datetime
    quantity: int
    unit_price: float

# create table advertising (
#  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS identity,
#  user_id UUID NOT NULL,
#  product_id int not null,
#  status text not null, -- ativo, inativo
#  expiration_timestamp TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo'),
#  quantity int not null default 0,
#  unit_price float not null default 0.0,
#  FOREIGN KEY (user_id) REFERENCES "user"(id),
#  foreign key (product_id) references product(id)
# );
