from pydantic import BaseModel
from typing import List

class CreateProductResponse(BaseModel):
    id: str

class ProductDTO(BaseModel):
    name: str
    description: str
    pictures: List[str] = []

# create table product(
# id integer primary key generated by default as identity,
# name text not null,
# description text not null,
# pictures TEXT[] NOT NULL
# ); -- pra inserir '{"imagem1.jpg", "imagem2.jpg", "imagem3.jpg"}'

