CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "user" (
	id UUID primary key DEFAULT (uuid_generate_v4()) NOT null,
	name text NOT NULL,
	email text NOT null unique
);

create table product(
	id integer primary key generated by default as identity,
	name text not null,
	description text not null,
	pictures TEXT[] NOT NULL
); -- pra inserir '{"imagem1.jpg", "imagem2.jpg", "imagem3.jpg"}'

create table advertising (
	 id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS identity,
	 user_id UUID NOT NULL,
	 product_id int not null,
	 status text not null, -- ativo, inativo
	 expiration_timestamp TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo'),
	 quantity int not null default 0,
	 unit_price float not null default 0.0,
	 FOREIGN KEY (user_id) REFERENCES "user"(id),
	 FOREIGN KEY (product_id) references product(id)
);

create table transaction(
	id UUID primary key DEFAULT (uuid_generate_v4()) NOT null,
	buyer_id UUID NOT NULL,
	seller_id UUID NOT NULL,
	value float not null,
	created_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo'),
	FOREIGN KEY (buyer_id) REFERENCES "user"(id),
	FOREIGN KEY (seller_id) REFERENCES "user"(id)
);

create table "order"(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS identity,
	transaction_id UUID,
	advertising_id int not null,
	price float not null,
	created_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo'),
	foreign key (transaction_id) references "transaction"(id),
	foreign key (advertising_id) references advertising(id)
);
